## First Model

In [ ]:
import numpy as np
import re
import nltk
from sklearn.datasets import load_files
nltk.download('stopwords')
import pickle
from nltk.corpus import stopwords
import pandas as pd
import re

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [ ]:
our_dict = {0:"workout",1:"diet for next days",2:"diet for today"}

In [ ]:
data = pd.read_csv('data.csv',header=None,delimiter=";")

In [ ]:
data.head()

0  1         2
0         how should I work out for jul 1th  0   jul 1th
1            what is the workout on aug 3rd  0   aug 3rd
2              what should I work out today  0     today
3         Hey what should I work out monday  0    monday
4  hello how should I work out for june 2nd  0  june 2nd

In [ ]:
data.tail()

0  1          2
395        hello what is the meal for lunch  2      lunch
396           what's the diet for breakfast  2  breakfast
397  hi what do I have to eat for breakfast  2  breakfast
398          what's the diet plan for lunch  2      lunch
399       hey what's the meal for breakfast  2  breakfast

In [ ]:
X, y = data[0],data[1]


In [ ]:
X

0             how should I work out for jul 1th
1                what is the workout on aug 3rd
2                  what should I work out today
3             Hey what should I work out monday
4      hello how should I work out for june 2nd
                         ...                   
395            hello what is the meal for lunch
396               what's the diet for breakfast
397      hi what do I have to eat for breakfast
398              what's the diet plan for lunch
399           hey what's the meal for breakfast
Name: 0, Length: 400, dtype: object

In [ ]:
months = "january|february|march|april|may|june|july|august|september|octember|november|december"
months = months.split("|")
print(months)
vocab = ""
for month in months:
  for i in range(len(month)+1):
    vocab = vocab + month[:i] + "|"
  vocab = vocab[:-1]

['january', 'february', 'march', 'april', 'may', 'june', 'july', 'august', 'september', 'octember', 'november', 'december']


In [ ]:
months = {"january":1,"february":2,"march":3,"april":4,"may":5,"june":6,"july":7,"august":8,"september":9,"octember":10,"november":11,"december":12}

In [ ]:
def make_vocab():
  months = "january|february|march|april|may|june|july|august|september|octember|november|december"
  months = months.split("|")
  vocab = ""
  time = 0
  while True:
    for month in months:
      if len(month)>=3:
        vocab = vocab + month + "|"
    for i in range(len(months)):
      if months[i] != "":
        months[i] = months[i][:-1]
      else: time +=1
    
    if time > 11:
      break
    else: time = 0
  return vocab



In [ ]:
regex = "\w*\d+\w{0,3}"

In [ ]:
m = re.match(r".*(\d+).*("+vocab[:-1]+")", " the 3rd of jul")


In [ ]:
print(m.group(2))

In [ ]:
# date = ["january","february","march,"]

In [ ]:
def find_month(x,vocab):
  m = re.match(r".*(\d+).*("+vocab[:-1]+")", x)
  if m:
    return m.group(1),m.group(2)
  else:
    m = re.match(r".*("+vocab[:-1]+").*(\d+)", x)
    if m: return m.group(2),m.group(1)
    else: return None,None


In [ ]:
def find_day(x):
  m = re.match(r".*(today|tomorrow|yesterday|next day|nextday)", x)
  if m:
    return m.group(1)
  else: return None


In [ ]:
def find_week_day(x):
  m = re.match(r".*(monday|tuesday|wednesday|thursday|friday|saturday|sunday)", x)
  if m:
    return m.group(1)
  else: return None

In [ ]:
def find_meal_time(x):
  m = re.match(r".*(lunch|dinner|supper|brunch|breakfast)", x)
  if m:
    return m.group(1)
  else: return None

In [ ]:
from datetime import datetime 

# to get hour from datetime
print('Hour: ', todays_date.year)

# to get minute from datetime
print('Minute: ', todays_date.month)

Hour:  2021
Minute:  11


In [ ]:
def make_key_month(months):
  # print(months.items)
  new_dict = {}
  for key,value in months.items():
    word = key
    i = 0

    # print(word)
    while len(word) >= 3:
      
      new_dict[word] = value
      i += 1
      word = key[:-i]

      # print(new_dict)
  print(new_dict)
  return new_dict

In [ ]:
my_string = '2019-10-31'

# Create date object in given time format yyyy-mm-dd
my_date = datetime.strptime(my_string, "%Y-%m-%d")

print(my_date)
print('Type: ',type(my_date))

2019-10-31 00:00:00
Type:  <class 'datetime.datetime'>


In [ ]:
from datetime import datetime
from datetime import timedelta
import calendar


def find_date(X):
  months = {"january":1,"february":2,"march":3,"april":4,"may":5,"june":6,"july":7,"august":8,"september":9,"octember":10,"november":11,"december":12}
  days_not_digit = {"today":0,"tomorrow":1,"next day":1,"nextday":1}
  week_days = {"monday":1,"tuesday":2,"wednesday":3,"thursday":4,"friday":5,"saturday":6,"sunday":7}
  '''monday|tuesday|wednesday|thursday|friday|saturday|sunday'''
  week_days
  months = make_key_month(months)
  todays_date = datetime.now()
  day_type = {}
  vocab = make_vocab()
  print(f"Vocab is\n{vocab}")
  print(f"sentence:\n{X}")
  day, month = find_month(X,vocab)
  # if not day:
  day_not_digit = find_day(X)
  # if not day:
  week_day = find_week_day(X)
  # if not day:
  meal_time = find_meal_time(X)
    
    # print("Date is")
  if day and month:
    my_string = str(todays_date.year)+"-"+str(months[month])+"-"+str(day)
    my_date = datetime.strptime(my_string, "%Y-%m-%d")  
    # print(my_date)
  if day_not_digit:
    digit = days_not_digit[day_not_digit]
    date_diet = datetime.today() + timedelta(days=digit)
    my_string = str(date_diet.year)+"-"+str(date_diet.month)+"-"+str(date_diet.day)
    my_date = datetime.strptime(my_string, "%Y-%m-%d")  
    # print(my_date)
  if week_day:
    distance = week_days[week_day] - week_days[str(calendar.day_name[todays_date.weekday()]).lower()]
    if distance < 0:
      distance += 7
    date_diet = datetime.today() + timedelta(days=distance)
    my_string = str(date_diet.year)+"-"+str(date_diet.month)+"-"+str(date_diet.day)
    my_date = datetime.strptime(my_string, "%Y-%m-%d")  

    return my_date,meal_time


In [ ]:

print(find_date(X[0]))

{'january': 1, 'januar': 1, 'janua': 1, 'janu': 1, 'jan': 1, 'february': 2, 'februar': 2, 'februa': 2, 'febru': 2, 'febr': 2, 'feb': 2, 'march': 3, 'marc': 3, 'mar': 3, 'april': 4, 'apri': 4, 'apr': 4, 'may': 5, 'june': 6, 'jun': 6, 'july': 7, 'jul': 7, 'august': 8, 'augus': 8, 'augu': 8, 'aug': 8, 'september': 9, 'septembe': 9, 'septemb': 9, 'septem': 9, 'septe': 9, 'sept': 9, 'sep': 9, 'octember': 10, 'octembe': 10, 'octemb': 10, 'octem': 10, 'octe': 10, 'oct': 10, 'november': 11, 'novembe': 11, 'novemb': 11, 'novem': 11, 'nove': 11, 'nov': 11, 'december': 12, 'decembe': 12, 'decemb': 12, 'decem': 12, 'dece': 12, 'dec': 12}
Vocab is
january|february|march|april|may|june|july|august|september|octember|november|december|januar|februar|marc|apri|jun|jul|augus|septembe|octembe|novembe|decembe|janua|februa|mar|apr|augu|septemb|octemb|novemb|decemb|janu|febru|aug|septem|octem|novem|decem|jan|febr|septe|octe|nove|dece|feb|sept|oct|nov|dec|sep|
sentence:
how should I work out for jul 1th
Non

In [ ]:
def convert_date(X):
  find

In [ ]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    2
396    2
397    2
398    2
399    2
Name: 1, Length: 400, dtype: int64

In [ ]:
documents = []

from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')
stemmer = WordNetLemmatizer()

for sen in range(0, len(X)):
    # Remove all the special characters
    document = re.sub(r'\W', ' ', str(X[sen]))
    
    # remove all single characters
    document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)
    
    # Remove single characters from the start
    document = re.sub(r'\^[a-zA-Z]\s+', ' ', document) 
    
    # Substituting multiple spaces with single space
    document = re.sub(r'\s+', ' ', document, flags=re.I)
    
    # Removing prefixed 'b'
    document = re.sub(r'^b\s+', '', document)
    
    # Converting to Lowercase
    document = document.lower()
    
    # Lemmatization
    document = document.split()

    document = [stemmer.lemmatize(word) for word in document]
    document = ' '.join(document)
    
    documents.append(document)

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


In [ ]:
documents

['how should work out for jul 1th',
 'what is the workout on aug 3rd',
 'what should work out today',
 'hey what should work out monday',
 'hello how should work out for june 2nd',
 'hey what the work out april 3rd',
 'what is the work out tomorrow',
 'how should work out for feb 2nd',
 'what should work out jun 16',
 'hello how should work out for monday',
 'hey what should work out february 2nd',
 'how should work out for friday',
 'how should work out for dec 29th',
 'hello how should work out for feb 3rd',
 'what should work out the next day',
 'hello what should work out january 2nd',
 'what is the workout plan on monday',
 'what is the workout plan on the next day',
 'what should work out nov 24th',
 'hi how should work out for saturday',
 'how should work out for sunday',
 'hello how should work out for the next day',
 'what the work out plan on aug 16th',
 'what should work out mar 2nd',
 'hello what should work out tomorrow',
 'hey how should work out for may 24th',
 'hello wh

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(max_features=1500, min_df=5, max_df=0.7, stop_words=stopwords.words('english'))
X = vectorizer.fit_transform(documents).toarray()

In [ ]:
vectorizer

CountVectorizer(max_df=0.7, max_features=1500, min_df=5,
                stop_words=['i', 'me', 'my', 'myself', 'we', 'our', 'ours',
                            'ourselves', 'you', "you're", "you've", "you'll",
                            "you'd", 'your', 'yours', 'yourself', 'yourselves',
                            'he', 'him', 'his', 'himself', 'she', "she's",
                            'her', 'hers', 'herself', 'it', "it's", 'its',
                            'itself', ...])

In [ ]:
X[0],documents[0]

(array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0]), 'how should work out for jul 1th')

In [ ]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidfconverter = TfidfTransformer()
X = tfidfconverter.fit_transform(X).toarray()

In [ ]:
tfidfconverter
joblib.dump(tfidfconverter, "./tfidfconverter.joblib")


['./tfidfconverter.joblib']

In [ ]:
X

array([[0.38456403, 0.        , 0.        , ..., 0.        , 0.1587613 ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.44953494],
       [0.        , 0.        , 0.        , ..., 0.        , 0.32066209,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
y_train

336    2
64     0
55     0
106    0
300    1
      ..
323    2
192    1
117    0
47     0
172    1
Name: 1, Length: 320, dtype: int64

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=1000, random_state=0)
classifier.fit(X_train, y_train) 

RandomForestClassifier(n_estimators=1000, random_state=0)

In [ ]:
X_test

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.50111608],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.37496577, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
y_pred = classifier.predict(X_test)


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[35  0  0]
 [ 0 31  1]
 [ 0  0 13]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        35
           1       1.00      0.97      0.98        32
           2       0.93      1.00      0.96        13

    accuracy                           0.99        80
   macro avg       0.98      0.99      0.98        80
weighted avg       0.99      0.99      0.99        80

0.9875


In [ ]:
import joblib


In [ ]:
joblib.dump(classifier, "./random_forest.joblib")


['./random_forest.joblib']

In [ ]:
loaded_rf = joblib.load("./random_forest.joblib")
y_pred = loaded_rf.predict(X_test)


In [ ]:
joblib.dump(vectorizer, "./vectorizer.joblib")


['./vectorizer.joblib']

In [ ]:
vectorizer = joblib.load("./vectorizer.joblib")


In [ ]:
vectorizer

CountVectorizer(max_df=0.7, max_features=1500, min_df=5,
                stop_words=['i', 'me', 'my', 'myself', 'we', 'our', 'ours',
                            'ourselves', 'you', "you're", "you've", "you'll",
                            "you'd", 'your', 'yours', 'yourself', 'yourselves',
                            'he', 'him', 'his', 'himself', 'she', "she's",
                            'her', 'hers', 'herself', 'it', "it's", 'its',
                            'itself', ...])

In [ ]:
type(vectorizer)

sklearn.feature_extraction.text.CountVectorizer

In [ ]:
vectorizer = CountVectorizer(max_features=1500, min_df=5, max_df=0.7, stop_words=stopwords.words('english'))
# X = vectorizer.fit_transform(documents).toarray()
docs_new = ["What is my diet for lunch?"]
X_new_counts = vectorizer.transform(docs_new)
X_new_tfidf = tfidfconverter.transform(X_new_counts)

predicted = classifier.predict(X_new_tfidf)

for doc, category in zip(docs_new, predicted):
  print('%r => %s' % (doc,our_dict[category]))

NotFittedError: ignored

## Second Model

In [ ]:
  import numpy
from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import SpatialDropout1D
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence
from sklearn.model_selection import train_test_split
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import SnowballStemmer
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
import regex as re
import string
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
import gensim
from gensim.models import Word2Vec

In [ ]:
# fix random seed for reproducibility
numpy.random.seed(7)
# load the dataset but only keep the top n words, zero the rest
top_words = 5000
data = pd.read_csv('data.csv',header=None,delimiter=";")
# X, y = data[0],data[1]
# X_train, y_train, X_test, y_test = train_test_split(X,y,test_size = 0.3)


In [ ]:
#convert to lowercase, strip and remove punctuations
def preprocess(text):
    text = text.lower() 
    text=text.strip()  
    text=re.compile('<.*?>').sub('', text) 
    text = re.compile('[%s]' % re.escape(string.punctuation)).sub(' ', text)  
    text = re.sub('\s+', ' ', text)  
    # text = re.sub(r'\[[0-9]*\]',' ',text) 
    text=re.sub(r'[^\w\s]', '', str(text).lower().strip())
    # text = re.sub(r'\d',' ',text) 
    text = re.sub(r'\s+',' ',text) 
    return text

 
# STOPWORD REMOVAL
def stopword(string):
    a= [i for i in string.split() if i not in stopwords.words('english')]
    return ' '.join(a)

# Initialize the lemmatizer
wl = WordNetLemmatizer()
 
# This is a helper function to map NTLK position tags
def get_wordnet_pos(tag):
    if tag.startswith('J'):
        return wordnet.ADJ
    elif tag.startswith('V'):
        return wordnet.VERB
    elif tag.startswith('N'):
        return wordnet.NOUN
    elif tag.startswith('R'):
        return wordnet.ADV
    else:
        return wordnet.NOUN

# Tokenize the sentence
def lemmatizer(string):
    word_pos_tags = nltk.pos_tag(word_tokenize(string))
    a=[wl.lemmatize(tag[0], get_wordnet_pos(tag[1])) for idx, tag in enumerate(word_pos_tags)] 
    return " ".join(a)

In [ ]:
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [ ]:
def finalpreprocess(string):
  return lemmatizer(stopword(preprocess(string)))
data['clean_text'] = data[0].apply(lambda x: finalpreprocess(x))
data.head()

0  1         2           clean_text
0         how should I work out for jul 1th  0   jul 1th         work jul 1th
1            what is the workout on aug 3rd  0   aug 3rd      workout aug 3rd
2              what should I work out today  0     today           work today
3         Hey what should I work out monday  0    monday      hey work monday
4  hello how should I work out for june 2nd  0  june 2nd  hello work june 2nd

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data[0],data[1],test_size=0.1,shuffle=True)


In [ ]:
X_train

135                 what should I work out aug 3rd
111             how should I work out for apr 07th
251                  Hi what can I eat october 3rd
206                 what should I eat the next day
170              hi what do I have to eat tomorrow
                          ...                     
143       how should I work out for september 24th
16              what is the workout plan on monday
129            how should I work out for march 3rd
137    Hey how should I work out for december 24th
368               what is the diet plan for dinner
Name: 0, Length: 360, dtype: object

In [ ]:
import tensorflow as tf

In [ ]:
VOCAB_SIZE = 1000
encoder = tf.keras.layers.TextVectorization(
    max_tokens=VOCAB_SIZE)
encoder.adapt(X_train.map(lambda text, label: text))

In [ ]:
vectorizer = CountVectorizer(max_features=1500, min_df=5, max_df=0.7, stop_words=stopwords.words('english'))
X = vectorizer.fit_transform(X_train).toarray()

In [ ]:
X

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 1, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data["clean_text"],data[1],test_size=0.2,shuffle=True)
#Word2Vec
# Word2Vec runs on tokenized sentences
X_train_tok= [nltk.word_tokenize(i) for i in X_train]  
X_test_tok= [nltk.word_tokenize(i) for i in X_test]

In [ ]:
X_train_tok[0]

['workout', 'apr', '1th']

In [ ]:
X_train

216            eat tomorrow
229              eat friday
392        hello meal lunch
135            work aug 3rd
130    workout plan tuesday
               ...         
377           hi eat dinner
124      hi work plan today
20              work sunday
113      hello work may 3rd
180             eat tuesday
Name: clean_text, Length: 320, dtype: object

In [ ]:
#Tf-Idf
tfidf_vectorizer = TfidfVectorizer(use_idf=True)
X_train_vectors_tfidf = tfidf_vectorizer.fit_transform(X_train) 
X_test_vectors_tfidf = tfidf_vectorizer.transform(X_test)
#building Word2Vec model
class MeanEmbeddingVectorizer(object):
    def __init__(self, word2vec):
        self.word2vec = word2vec
        # if a text is empty we should return a vector of zeros
        # with the same dimensionality as all the other vectors
        self.dim = len(next(iter(word2vec.values())))
def fit(self, X, y):
        return self
def transform(self, X):
        return np.array([
            np.mean([self.word2vec[w] for w in words if w in self.word2vec]
                    or [np.zeros(self.dim)], axis=0)
            for words in X
        ])

model = Word2Vec(data['clean_text_tok'],min_count=1)    
w2v = dict(zip(model.wv.index2word, model.wv.syn0)) 
data['clean_text_tok']=[nltk.word_tokenize(i) for i in data['clean_text']] 
modelw = MeanEmbeddingVectorizer(w2v)
# converting text to numerical data using Word2Vec
X_train_vectors_w2v = modelw.transform(X_train_tok)
X_val_vectors_w2v = modelw.transform(X_test_tok)

KeyError: ignored

In [ ]:
# truncate and pad input sequences
max_review_length = 500
X_train = sequence.pad_sequences(X_train, maxlen=max_review_length)
X_test = sequence.pad_sequences(X_test, maxlen=max_review_length)

ValueError: ignored

In [ ]:
X

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 1, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
X.shape[1]

45

In [ ]:
from tensorflow.keras.optimizers import Adam,SGD


In [ ]:
lr = 8e-5
decay_rate = 1e-4
# create the model
embedding_vecor_length = 16
model = Sequential()

model.add(Embedding(1500, len(X), input_length=len(X[1])))
model.add(SpatialDropout1D(0.2))
model.add(LSTM(100, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1, activation='softmax'))
opt = Adam(learning_rate=lr, decay=decay_rate)
model.compile(loss='categorical_crossentropy', optimizer=opt, metrics=['accuracy'])
print(model.summary())
model.fit(X, y_train, epochs=300, batch_size=64)


Model: "sequential_21"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_12 (Embedding)    (None, 45, 360)           540000    
                                                                 
 spatial_dropout1d_9 (Spatia  (None, 45, 360)          0         
 lDropout1D)                                                     
                                                                 
 lstm_11 (LSTM)              (None, 100)               184400    
                                                                 
 dense_11 (Dense)            (None, 1)                 101       
                                                                 
Total params: 724,501
Trainable params: 724,501
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/300
6/6 [==============================] - 4s 240ms/step - loss: 0.0000e+00 - accuracy: 0.3917
Epoch

KeyboardInterrupt: ignored

In [ ]:
# Final evaluation of the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))

In [ ]:
our_dict = {0:"workout",1:"diet for next days",2:"diet for today"}

In [ ]:
(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=1)

17473536/17464789 [==============================] - 0s 0us/step


In [ ]:
X_train[0]

[2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2]